theme: jekyll-theme-cayman
title: Rotation Axis Focused Attention Network (RAFA-Net) for Estimating Head Pose
description:  15th Asian Conference on Computer Vision (ACCV) 2020
github:
  is_project_page: false
